theme: jekyll-theme-modernist

title: René Parlange
description: MSc. in Computer Science, Instituto Nacional de Astrofísica, Óptica y Electrónica.
<img src="https://github-readme-stats.vercel.app/api?username=parlange&show_icons=true"/>
show_downloads: false
google_analytics: 72933942
